const dogs = [
  {
    id: "1",
    name: "Buddy",
    breed: "Golden Retriever",
    age: 3,
    size: "Large",
    gender: "Male",
    temperament: "Friendly, Energetic",
    image: "/images/dogs/buddy.jpg",
    description: "Loves playing fetch and is great with kids.",
  },
  {
    id: "2",
    name: "Luna",
    breed: "Beagle",
    age: 2,
    size: "Medium",
    gender: "Female",
    temperament: "Energetic and friendly",
    image: "/images/dogs/luna.jpg",
    description: "Loves belly rubs and is very curious.",
  },
  {
    id: "3",
    name: "Max",
    breed: "Labrador",
    age: 4,
    size: "Large",
    gender: "Male",
    temperament: "Gentle, Calm",
    image: "/images/dogs/max.jpg",
    description: "Gentle giant with a calm personality.",
  },
  {
    id: "4",
    name: "Dogesh",
    breed: "Mixed Breed",
    age: 4,
    size: "Medium",
    gender: "Male",
    temperament: "Chill, Playful",
    image: "/images/dogs/dogesh.jpg",
    description: "Very chill. Good boi. Much wow.",
  },
  {
    id: "5",
    name: "Hassu",
    breed: "Husky",
    age: 2,
    size: "Large",
    gender: "Female",
    temperament: "Talkative, Fluffy",
    image: "/images/dogs/hassu.jpg",
    description: "Talkative and super fluffy!",
  },
  {
    id: "6",
    name: "Jerry",
    breed: "German Shepherd",
    age: 7,
    size: "Large",
    gender: "Male",
    temperament: "Loyal, Protective, Well-trained",
    image: "/images/dogs/jerry.jpg",
    description: "Loyal protector and well-trained.",
  },
  // New dogs added
  {
    id: "7",
    name: "Bella",
    breed: "Poodle",
    age: 5,
    size: "Medium",
    gender: "Female",
    temperament: "Intelligent, Friendly",
    image: "/images/dogs/bella.jpg",
    description: "Loves cuddles and learning tricks.",
  },
  {
    id: "8",
    name: "Charlie",
    breed: "Bulldog",
    age: 6,
    size: "Medium",
    gender: "Male",
    temperament: "Calm, Courageous",
    image: "/images/dogs/charlie.jpg",
    description: "Strong and calm, perfect family companion.",
  },
  {
    id: "9",
    name: "Molly",
    breed: "Dachshund",
    age: 3,
    size: "Small",
    gender: "Female",
    temperament: "Curious, Playful",
    image: "/images/dogs/molly.jpg",
    description: "Small but full of energy and love.",
  },
  {
    id: "10",
    name: "Rocky",
    breed: "Boxer",
    age: 4,
    size: "Large",
    gender: "Male",
    temperament: "Energetic, Protective",
    image: "/images/dogs/rocky.jpg",
    description: "Loves to play and protect his family.",
  },
  {
    id: "11",
    name: "Daisy",
    breed: "Shih Tzu",
    age: 2,
    size: "Small",
    gender: "Female",
    temperament: "Affectionate, Gentle",
    image: "/images/dogs/daisy.jpg",
    description: "Loves to cuddle and is very gentle with kids.",
  },
];

export default dogs;
